# site settings
title: Curtis West
subtitle: Australia
email: curtis@curtiswest.net
description: I'm a Data Analytics Specialist and Software Engineer. Motivated, strategically-aligned and outcomes-focussed.
baseurl:  # the subpath of your site, e.g. /blog
url: "https://curtiswest.net" # the base hostname & protocol for your site
author: Curtis West
street_address: 
city: Brisbane
state: QLD
zip_code: 4000
country: Australia
phone:
permalink: pretty

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 4

# social settings
500px_url:
facebook_url:
github_url: https://github.com/curtiswest/
gitlab_url: 
googleplus_url: 
instagram_url: https://instagram.com/seewesty
linkedin_url: https://www.linkedin.com/in/curtiswest
pinterest_url:
slack_url:
twitter_url: 
flickr_url: https://flickr.com

# build settings
markdown: kramdown

sass:
  style: compressed
